// GENERATED by control-center/scripts/build-web.mjs - do not hand-edit.
// Fetch hamqsl band conditions and write band-conditions.json (run by the hourly
// Action in CI, where CORS does not apply). Keeps the last good file on any
// fetch/parse failure, and only rewrites when the band VALUES actually change.
// Uses an explicit AbortController + clearTimeout so the process exits cleanly
// (no dangling timer) instead of needing process.exit().
import { readFileSync, writeFileSync } from "node:fs";
import { parseSolar } from "./feeds/solar.js";

const SRC = "https://www.hamqsl.com/solarxml.php";
const OUT = "band-conditions.json";

async function main() {
  const ac = new AbortController();
  const t = setTimeout(() => ac.abort(), 20000);
  let xml;
  try {
    const res = await fetch(SRC, { signal: ac.signal });
    if (!res.ok) { console.error("hamqsl HTTP " + res.status + "; keeping last good"); return; }
    xml = await res.text();
  } finally { clearTimeout(t); }

  const parsed = parseSolar(xml);
  if (!parsed || !parsed.bands || !Object.keys(parsed.bands).length) {
    console.error("no bands parsed; keeping last good"); return;
  }
  let prev = null;
  try { prev = JSON.parse(readFileSync(OUT, "utf8")); } catch { /* first run */ }
  const next = { fetchedAt: new Date().toISOString(), updated: parsed.updated || null, bands: parsed.bands };
  if (prev && JSON.stringify(prev.bands) === JSON.stringify(next.bands)) {
    console.log("bands unchanged; no write"); return;
  }
  writeFileSync(OUT, JSON.stringify(next, null, 2) + "\n");
  console.log("wrote " + Object.keys(next.bands).length + " band groups");
}
main().catch((e) => { console.error("fetch-bands failed; keeping last good:", e.message); });
